//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Apple.rc에서 사용되고 있습니다.
//
#define IDS_ABOUTBOX                    101
#define IDD_Apple_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDC_RADIO_2D                    1008
#define IDC_RADIO_3D                    1009
#define IDC_EDIT_PASSWORD               1009
#define IDC_RADIO_3D2                   1010
#define IDC_RADIO_NGRV                  1010
#define IDC_CMB_THREAD_NUMBER           1013
#define IDC_EDIT_LED_DURATION           1014
#define IDC_EDIT_GRAB_DURATION          1015
#define IDC_CMB_HANDLER_TYPE            1016
#define IDC_CMB_THREAD_NUMBER2          1017
#define IDC_CMB_GRAB_BUFFER_NUMBER      1017
#define IDC_CMB_FRAME_GRABBER_TYPE      1018
#define IDC_CMB_NGRV_OPTICS_TYPE        1019
#define IDC_CMB_2DVISION_CAMERA_TYPE    1020
#define IDC_CMB_3DVISION_CAMERA_TYPE    1021
#define IDC_CMB_3DVISION_CAMERA_NUMBER  1022
#define IDC_CHECK_USE_AI_INSPECTION     1026
#define IDC_EDIT_WAIT_TIME_SEND_DATA    1027
#define IDC_CHECK_USE_BAYER_PATTERN_GPU 1028
#define IDC_CHECK_USE_LONG_EXPOSURE     1029
#define IDC_COMBO_IR_CHANNEL_ID         1030
#define IDC_COMBO_UV_CHANNEL_ID         1031
#define IDC_EDIT_DEFAULT_CHANNEL_GAIN_VALUE 1032
#define IDC_EDIT_IR_CHANNEL_GAIN_VALUE  1033
#define IDC_EDIT_UV_CHANNEL_GAIN_VALUE  1034
#define IDC_COMBO_IR_CHANNEL_ID2        1035
#define IDC_COMBO_COAXIAL_ILLUMINATION_CALIBRATION_TYPE 1035
#define IDC_CHECK1                      1036
#define IDC_CHECK_USE_RING_ILLUMINATION 1036
#define IDC_CMB_VISION_TYPE             1037
#define IDC_COMBO2                      1038
#define IDC_COM_SIDE_VISION_NUMBER      1038
#define IDC_CMB_SIDE_VISION_NUMBER      1038
#define IDC_STATIC_NGRV_COLOR_PARAM_BOX 1039
#define IDC_STATIC_IR_CHANNEL_ID        1040
#define IDC_STATIC_UV_CHANNEL_ID        1041
#define IDC_STATIC_DEFAULT_CAM_GAIN     1042
#define IDC_STATIC_IR_CHANNEL_GAIN      1043
#define IDC_STATIC_UV_CHANNEL_GAIN      1044
#define IDC_STATIC_NGRV_OPTICS_TYPE     1045
#define IDC_STATIC_LED_DURATION         1046
#define IDC_STATIC_GRAB_DURATION        1047
#define IDC_STATIC_COAXIAL_ILLUMINATION_CALIBRATION_TYPE 1048
#define IDC_STATIC_SIDE_VISION_NUMBER   1049
#define IDC_STATIC_WAIT_TIME_SEND_DATA  1050
#define IDC_STATIC_WAIT_TIME_SEC        1051
#define IDC_STATIC_2D_CAMERA_TYPE       1052
#define IDC_STATIC_2DVISION_CAMERA_TYPE 1052
#define IDC_STATIC_3DVISION_CAMERA_TYPE 1053
#define IDC_STATIC_CAMERA_NUMBER        1054
#define IDC_CHECK_HARDWARE_EXIST        14007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
